services:
  web:
    build: .
    container_name: fastapi_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    command: celery -A app.celery_config.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/app/static

  telegram_bot:
    build: .
    container_name: telegram_bot
    command: python telegram_bot.py
    env_file:
      - .env
    depends_on:
      - web
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:

